### ISSUE TITLE
kissmanga download error

### ISSUE THREAD

**Issue by dawnlodd** [NguyenDanPhuong/MangaRipper#60] opened 2017-03-20 16:19 UTC
i dont know if this is an issue with my pc, but the mangaripper.core keeps sending me a message about how it cant access the chapters of the manga i want it to download. i tried messing with the code but couldnt do anything about it. downloaded again but the issue still there.

this only happens with kissmanga. everything is working fine but cant get anything from kissmanga.

anyone having this issue or just me?

(sorry about english grammar but im not english native)

**Comment by JedBurke** [comment] 2017-03-20 16:49
Hi, which version of Windows and the application are you using?

**Comment by NguyenDanPhuong** [comment] 2017-03-21 15:47
I've just do a quick debug. MangaKiss now encrypted image's url using AES. It'll take some time to bypass this.

function wrapKA(base64EncodedUrl)
{
    var decryptedUrl=null;
    try
    {
        var _0xfac5x1d=CryptoJS["lib"]["CipherParams"]["create"]
        (
            {
                ciphertext:CryptoJS["enc"]["Base64"]["parse"](base64EncodedUrl)
            });
                var _0xfac5x1e=CryptoJS["AES"]["decrypt"](_0xfac5x1d,key,
                {
                    mode:CryptoJS["mode"]["CBC"],
                    iv:iv,
                    padding:CryptoJS["pad"]["Pkcs7"]
                });
                decryptedUrl=_0xfac5x1e.toString(CryptoJS["enc"].Utf8);
        return decryptedUrl
    }
    catch(err)
    {
        alert(err)
    }
}

**Comment by NguyenDanPhuong** [comment] 2017-03-22 13:32
I've fixed KissManga. However the fix affect startup time. It takes longer for MangaRipper to start. You can try with latest source code.

**Comment by GambitKZ** [comment] 2017-03-23 09:19
Guys, I have wrote the code without phantomJS, to pass the encryption.
I have checked it against 3 titles, and it looks good so far.

**Comment by JedBurke** [comment] 2017-03-23 09:54
@GambitKZ Was working on a fix using Jurassic. Nice getting it done without a JS lib. :grin:

**Comment by NguyenDanPhuong** [comment] 2017-03-23 11:56
Amazing guys. Lets use the fix from @GambitKZ, Using PhantomJS was my laziness. :D

@GambitKZ: Can you help resolve conflict in the pull request?

**Comment by GambitKZ** [comment] 2017-03-23 12:39
@NguyenDanPhuong 
We get it because as a base, I have used commit before phantomeJs.
We have two option here:
1) Rebase to previous version and force push from your side
2) Update dev branch, merge into feature, fix conflicts, That from my side.

We can go with whatever option you like. However I will be able to start on option two in a hour or so.

**Comment by JedBurke** [comment] 2017-03-23 13:34
> Using PhantomJS was my laziness.

@NguyenDanPhuong But it still got the job done. :) Should events like these persist, maybe emulating a browser isn't such a bad idea.

**Comment by GambitKZ** [comment] 2017-03-23 13:49
@JedBurke Maybe it's better to rewrite the code with HttpClient? Like you did previously.

**Comment by JedBurke** [comment] 2017-03-23 14:08
@GambitKZ I think for the time being, you guys have the solution. Though it's clear what was intended with the encryption and wouldn't be surprised to see the keys change soon.

**Comment by GambitKZ** [comment] 2017-03-23 14:22
@NguyenDanPhuong I have fixed the code. Now It can be merged.

**Comment by NguyenDanPhuong** [comment] 2017-03-24 08:21
Guys, let keep monitoring the situation. If KissManga keeps changing. We may consider using PhantomJS.

**Comment by JedBurke** [comment] 2017-03-24 09:38
Site's up again.

**Comment by GambitKZ** [comment] 2017-03-24 15:31
Test passed. Looks like everything ok for now.

b.t.w. Maybe CryptoJS is a work of CloudFlare?

**Comment by NguyenDanPhuong** [comment] 2017-03-27 06:47
Hi guys, I refactor code and adapt the latest encryption scheme from KissManga.

**Closed by NguyenDanPhuong** 2017-03-27 06:47 UTC
