### ISSUE TITLE
MangaFox Error 

### ISSUE THREAD

**Issue by BaganLee** [NguyenDanPhuong/MangaRipper#39] opened 2017-01-20 11:57 UTC
Hello.  I get an error when i am trying to download a new chapter from mangafox i get this error: http://imgur.com/a/mdlxl . That happened only at MangaFox i have tried to download  many mangas from the same site to see if this is going to happening  again and it did happened again. I check and the other post about the mangaripper stop working but i didn't find anything useful. 
And here is me log : http://pastebin.com/REnTDBWp

**Comment by NguyenDanPhuong** [comment] 2017-01-20 13:25
From the log. It's seem that MangaFox server was having problem. The error is because app cannot open the url  http://mangafox.me/manga/onepunch_man/vTBD/c069/1.html 

Can you run it again? Can you open above url from your browser to see if it works.

**Comment by BaganLee** [comment] 2017-01-20 23:24
It opened from my browser. I tried to run it again and it give me the same error

**Comment by NguyenDanPhuong** [comment] 2017-01-21 12:16
This is seem to be a problem with MangaFox server. MangaHere is almost the same. Can you use it in the mean time. If this problem keep happening in the next few days. Please let me know. Thanks.

**Comment by NguyenDanPhuong** [comment] 2017-01-21 15:11
Ok. I think I've found the problem. :) MangaFox returns error when you made too many connections to their server in a short time. You may have run 2 instance of MangaRipper to download from MangaFox or download and browsing MangaFox at the same time.

**Comment by BaganLee** [comment] 2017-01-22 00:47
I tried again to download from mangafox and it give my the same error as the last time and i didn't have open any browser tab at mangafox and i give it a try with closed browser and again it give me the same error i am going to late it some days and see if something change  if not i am going to post here again and let you know.

**Comment by iYatsumi** [comment] 2017-01-22 01:58
@BaganLee i tried on my end with the latest release (version 1.0.173) with the same manga and it worked fine for me.



This might be a silly question but are you using the latest version ? because i as well used to have that same error but it was fixed when using the new release. 

And if you are already using the latest version could you upload once again the log ?

  

- %APPDATA%\MangaRipper\Logs

**Comment by CMDRGoro** [comment] 2017-01-22 10:09
I have same issue, i didn't go to mangafox at all today, not in broswer nor in manga ripper, log (im running 1.0173):

> 2017-01-22 11:04:41.6731 INFO > Main() 
2017-01-22 11:04:41.6901 INFO > Framework.Init() 
2017-01-22 11:04:41.6901 INFO > Worker() 
2017-01-22 11:04:41.8505 INFO Current Username: gufrohepra. New Username: gufrohepra 
2017-01-22 11:04:41.8505 INFO Current Password: 123. New Password: 123 
2017-01-22 11:04:45.1162 INFO > FindChapters: http://mangafox.me/manga/riki_oh/ 
2017-01-22 11:04:45.1232 INFO > FindChapters(): http://mangafox.me/manga/riki_oh/ 
2017-01-22 11:04:45.1232 INFO > DownloadStringAsync(String): http://mangafox.me/manga/riki_oh/ 
2017-01-22 11:04:45.4561 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-22 11:04:56.2438 INFO > DownloadChapter: http://mangafox.me/manga/riki_oh/v01/c001/1.html To: C:\Users\Grzyb\Desktop\My Mangas\test 
2017-01-22 11:04:56.2528 INFO > DownloadStringAsync(String): http://mangafox.me/manga/riki_oh/v01/c001/1.html 
2017-01-22 11:04:56.4905 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-22 11:04:56.4905 INFO > DownloadStringAsync(IEnumerable) - Total: 45 
2017-01-22 11:04:56.4905 INFO > DownloadStringAsync(String): http://mangafox.me/manga/riki_oh/v01/c001/1.html 
2017-01-22 11:04:56.5867 ERROR Failed to download chapter: http://mangafox.me/manga/riki_oh/v01/c001/1.html 
System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFoxService.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFoxService.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 57
2017-01-22 11:04:56.5977 ERROR System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFoxService.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFoxService.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 62
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<Run>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 50
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<StartDownload>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 141
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<btnDownload_Click>d__9.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 120 
System.Net.WebException: Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
   w System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   w System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Services.DownloadService.<DownloadStringAsync>d__11.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Services\DownloadService.cs:wiersz 76
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Plugin.MangaFox.MangaFoxService.<FindImanges>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Plugin.MangaFox\MangaFoxService.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<DownloadChapterInternal>d__7.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<>c__DisplayClass5_0.<<Run>b__0>d.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 62
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.Core.Controllers.WorkerController.<Run>d__5.MoveNext() w C:\projects\mangaripper\MangaRipper.Core\Controllers\WorkerController.cs:wiersz 50
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<StartDownload>d__10.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 141
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w MangaRipper.FormMain.<btnDownload_Click>d__9.MoveNext() w C:\projects\mangaripper\MangaRipper\Form\FormMain.cs:wiersz 120
2017-01-22 11:05:01.4356 INFO < Main()

**Comment by BaganLee** [comment] 2017-01-22 10:49
@iYatsumi Hello i have share my log but here >http://pastebin.com/KJ8sQFks . And yes i am using the latest version.

**Comment by iYatsumi** [comment] 2017-01-22 20:38
@BaganLee @CMDRGoro 

For now try using another website to download the manga you want from Mangaripper, it is unknown as to why Mangafox is working for some people and doesn't for others (Might be licenses or server issues). So until this issue is fixed, the best course of action is to use the other websites listed. 

- Bato.to
- Mangareader.com
- Read.mangashare.com
- etc. 

if those don't work either, do upload the log until the problem is resolve.

**Comment by BaganLee** [comment] 2017-02-10 23:30
Just a quick update  i don't have any problem with mangafox. And  because i want to ask a question and i don't want to open a new issues just for that, did you try to add the mangastream site too.

**Comment by NguyenDanPhuong** [comment] 2017-02-11 02:55
@BaganLee You should create another issue to request feature. It'll draw attention and someone may decide to work on it.

Since you don't have any problem with MangaFox. Let's close it.

**Closed by NguyenDanPhuong** 2017-02-11 02:55 UTC

**Comment by moax101** [comment] 2017-10-01 11:58
![image](https://user-images.githubusercontent.com/32432153/31054320-2909a286-a665-11e7-936f-101a10787812.png)
please how to fix this

**Comment by JedBurke** [comment] 2017-10-01 18:22
@moax101 Please see issue #95
